driftfile /var/lib/ntp/ntp.drift

restrict default kod nomodify notrap nopeer noquery
restrict 127.0.0.1
restrict ::1

# External time servers through NAT
pool 0.ubuntu.pool.ntp.org iburst
pool 1.ubuntu.pool.ntp.org iburst
pool 2.ubuntu.pool.ntp.org iburst
pool 3.ubuntu.pool.ntp.org iburst

# Allow DDP internal clients
restrict 192.168.100.0 mask 255.255.255.0 nomodify notrap

# Local fallback if internet/NAT is down
server 127.127.1.0
fudge 127.127.1.0 stratum 10
